Editor UI
Brett-Constantinoff/Quirk pull request #31
Opened 2024-07-02 01:00 UTC by maxsg5

This is a fairly large PR

### Summary of changes:
- Implementation of custom imgui windows into the Editor.
     - Panel classes based on the component class. 
         - ViewportPanel
         - ConsolePanel
         - LogPanel
         - SceneHierarchyPanel
         - MetricsPanel  
- Logo update

2024-07-04 02:34 UTC, Brett-Constantinoff requested changes
left some comments

2024-07-04 04:21 UTC, maxsg5 commented on editor/components/panels/ConsolePanel.cpp
> +    void ConsolePanel::Draw(const char* title, bool* p_open)
@Brett-Constantinoff TBH after looking through the code more, I don't know if I'm a big fan of using camelCase for function names. IMGUI for example uses PascalCase and also the Constructors use PascalCase anyways. 

Food for thought.

2024-07-04 04:27 UTC, maxsg5 commented on engine/display/DisplayWindow.hpp
> +#include "../core/eventSystem/events/ViewportResizeEvent.hpp"
Cannot remove this as the projection matrix calculation relies on this.

2024-07-04 04:33 UTC, maxsg5 commented
The requested changes should be implemented—re-requesting review for another set of eyes.

2024-07-04 14:19 UTC, Brett-Constantinoff commented on editor/components/panels/ConsolePanel.cpp
> +        : Component(title), m_HistoryPos(-1), m_AutoScroll(true), m_ScrollToBottom(false)
not a huge deal but again, for consistency, when initializing member variables in the constructor, use {} so it would be m_HistoryPos{-1}

2024-07-04 14:20 UTC, Brett-Constantinoff commented on editor/components/panels/ConsolePanel.cpp
> +        va_list args = {};
remove the = here, so it would just be char buf[1024]{};

2024-07-04 14:21 UTC, Brett-Constantinoff commented on editor/components/panels/ConsolePanel.cpp
> +        bool                reclaimFocus = false;
again use {} for initialization, so bool relcaimFocus{false}

2024-07-04 14:22 UTC, Brett-Constantinoff commented on editor/components/panels/ConsolePanel.cpp
> +        : Component(title), m_HistoryPos(-1), m_AutoScroll(true), m_ScrollToBottom(false)
i would also move everything but Component(title) to ConsolePanel.hpp

2024-07-04 14:23 UTC, Brett-Constantinoff commented on editor/components/panels/ConsolePanel.hpp
> +        void draw(const char* title, bool* pOpen = nullptr);
why are we taking in a bool* ? whats wrong with just a bool

2024-07-04 14:24 UTC, Brett-Constantinoff commented on editor/components/panels/ConsolePanel.hpp
> +        char m_InputBuf[256] = {}; // Text input buffer
these should all be initialized using {}

2024-07-04 14:24 UTC, Brett-Constantinoff commented on editor/components/panels/LogPanel.hpp
> +    void draw(const char* title, bool* pOpen = nullptr);
again, why with the bool*

2024-07-04 14:25 UTC, Brett-Constantinoff commented on editor/components/panels/ViewportPanel.cpp
> +                    Quirk::Engine::Renderer::Rendering::Renderer::setRenderModeWireframe();
for all these,, just add a 'using' statment

2024-07-04 14:26 UTC, Brett-Constantinoff commented on editor/utils/StringUtils.hpp
> +    // Compare two strings ignoring case
are these comments necessary?

2024-07-04 14:27 UTC, Brett-Constantinoff commented on engine/renderer/gui/ImguiImpl.cpp
> +        Quirk::Engine::Renderer::Utils::init_logging();
again, just add a using statement

2024-07-04 14:28 UTC, Brett-Constantinoff commented on engine/renderer/rendering/Renderer.hpp
> +        static void setRenderModeWireframe() noexcept;
are the noexcepts necessary here

2024-07-04 14:29 UTC, Brett-Constantinoff commented on engine/renderer/utils/ImGuiSink.hpp
> +   inline std::shared_ptr<ImGuiSink<std::mutex>> make_imgui_sink()
camelBack

2024-07-04 14:29 UTC, Brett-Constantinoff commented on engine/renderer/utils/ImGuiSink.hpp
> +   inline void init_logging()
camelBack

2024-07-04 14:31 UTC, Brett-Constantinoff commented on thirdParty/obj/Debug/assimp.Build.CppClean.log
all these files from thirdParty/obj/Debug shouldnt be committed i dont think

2024-07-04 15:48 UTC, maxsg5 commented on editor/components/panels/LogPanel.hpp
> +    void draw(const char* title, bool* pOpen = nullptr);
because ImGui::Begin takes a bool*

2024-07-04 15:50 UTC, maxsg5 commented on editor/utils/StringUtils.hpp
> +    // Compare two strings ignoring case
for a Util library I like to know what the function is doing.

2024-07-05 02:56 UTC, Brett-Constantinoff commented on editor/components/Component.cpp
> +    m_title = title;
we should be doing initialization like this 

`Component(const char *title) : 
 m_title{title}
 {
 }`

2024-07-05 02:57 UTC, Brett-Constantinoff commented on editor/components/panels/ConsolePanel.cpp
> +            const char *s = m_InputBuf;
{}

2024-07-05 02:58 UTC, Brett-Constantinoff commented on editor/components/panels/ConsolePanel.cpp
> +                    if (const char c = wordStart[-1]; c == ' ' || c == '\t' || c == ',' || c == ';')
this is so gross to look at and we can blame imgui for it lol, we might have to eventually re-write this anyways to fit our own needs but its good for now

2024-07-05 02:58 UTC, Brett-Constantinoff commented on editor/components/panels/ConsolePanel.cpp
> +                const char *wordEnd   = data->Buf + data->CursorPos;
{}

2024-07-05 02:58 UTC, Brett-Constantinoff commented on editor/components/panels/ConsolePanel.cpp
> +                const char *wordStart = wordEnd;
{}

2024-07-05 02:58 UTC, Brett-Constantinoff commented on editor/components/panels/ConsolePanel.cpp
> +                std::vector<const char *> candidates;
{}

2024-07-05 02:58 UTC, Brett-Constantinoff commented on editor/components/panels/ConsolePanel.cpp
> +                    uint32_t matchLen = static_cast<uint32_t>(wordEnd - wordStart);
{}

2024-07-05 02:59 UTC, Brett-Constantinoff commented on editor/components/panels/ConsolePanel.cpp
> +                        int32_t c                      = 0;
{}

2024-07-05 02:59 UTC, Brett-Constantinoff commented on editor/components/panels/ConsolePanel.cpp
> +                        bool    allCandidatesMatch = true;
{}

2024-07-05 02:59 UTC, Brett-Constantinoff commented on editor/components/panels/ConsolePanel.cpp
> +                        for (uint32_t i = 0; i < candidates.size() && allCandidatesMatch; i++)
{}

2024-07-05 02:59 UTC, Brett-Constantinoff commented on editor/components/panels/ConsolePanel.cpp
> +                const int32_t prevHistoryPos = m_HistoryPos;
{}

2024-07-05 02:59 UTC, maxsg5 commented on editor/components/panels/ConsolePanel.cpp
> +                    if (const char c = wordStart[-1]; c == ' ' || c == '\t' || c == ',' || c == ';')
lol yeah, they definitely wrote in a C-style

2024-07-05 02:59 UTC, Brett-Constantinoff commented on editor/components/panels/ConsolePanel.cpp
> +                    const char *history_str = (m_HistoryPos >= 0) ? m_History[m_HistoryPos] : "";
{}

2024-07-05 03:00 UTC, Brett-Constantinoff commented on editor/components/panels/ConsolePanel.cpp
> +                    const char *history_str = (m_HistoryPos >= 0) ? m_History[m_HistoryPos] : "";
also since this is a fairly important piece of code where speed is necessary, we could look into turning some of these const variables into constexpr

2024-07-05 03:00 UTC, Brett-Constantinoff commented on editor/components/panels/ConsolePanel.cpp
> +        ConsolePanel *console = static_cast<ConsolePanel *>(data->UserData);
{}

2024-07-05 03:01 UTC, Brett-Constantinoff commented on editor/components/panels/LogPanel.cpp
> +        int32_t oldSize = m_buf.size();
{}

2024-07-05 03:01 UTC, Brett-Constantinoff commented on editor/components/panels/LogPanel.cpp
> +        va_list args = {};
{}

2024-07-05 03:01 UTC, maxsg5 commented on editor/components/Component.cpp
> +    m_title = title;
🤡

2024-07-05 03:01 UTC, Brett-Constantinoff commented on editor/components/panels/LogPanel.cpp
> +        if (clearButton) clear();
try to keep these on separate lines, for readability

2024-07-05 03:01 UTC, Brett-Constantinoff commented on editor/components/panels/LogPanel.cpp
> +        const char* buf = m_buf.begin();
{}

2024-07-05 03:02 UTC, maxsg5 commented on editor/components/panels/ConsolePanel.cpp
> +            const char *s = m_InputBuf;
🤡

2024-07-05 03:32 UTC, Brett-Constantinoff commented on editor/components/panels/ConsolePanel.cpp
> +        char *allocatedMemory = static_cast<char *>(ImGui::MemAlloc(strlen(buf) + 1));
{}

2024-07-05 03:32 UTC, Brett-Constantinoff commented on editor/components/panels/ConsolePanel.cpp
> +        ImGuiInputTextFlags inputTextFlags =
{}

2024-07-05 03:33 UTC, Brett-Constantinoff commented on editor/components/panels/ConsolePanel.cpp
> +        for (auto it = m_History.begin(); it != m_History.end(); ++it)
{}

2024-07-05 03:33 UTC, Brett-Constantinoff commented on editor/components/panels/ConsolePanel.cpp
> +            uint64_t first = m_History.size() - 10;
{}

2024-07-05 03:33 UTC, Brett-Constantinoff commented on editor/components/panels/ConsolePanel.cpp
> +            for (uint64_t i = first > 0 ? first : 0; i < m_History.size(); ++i)
{}

2024-07-05 03:34 UTC, Brett-Constantinoff commented on editor/components/panels/LogPanel.hpp
> +        ImGuiTextBuffer      m_buf         = {};
direct list initialization plz

2024-07-05 03:35 UTC, Brett-Constantinoff commented on editor/core/Editor.cpp
> +        Timer timer = {};
direct

2024-07-05 03:35 UTC, Brett-Constantinoff commented on editor/core/Editor.hpp
> +        inline static MenuBar::MenuBar    m_menuBar;
{}

2024-07-05 03:35 UTC, Brett-Constantinoff commented on editor/utils/StringUtils.cpp
> +        uint32_t d = {};
direct

2024-07-05 03:35 UTC, Brett-Constantinoff commented on editor/utils/StringUtils.cpp
> +        uint32_t d = 0;
direct {}

2024-07-05 03:35 UTC, Brett-Constantinoff commented on editor/utils/StringUtils.cpp
> +        size_t len = strlen(s) + 1;
{}

2024-07-05 03:35 UTC, Brett-Constantinoff commented on editor/utils/StringUtils.cpp
> +        void* buf = new char[](len);
{}

2024-07-05 03:35 UTC, Brett-Constantinoff commented on editor/utils/StringUtils.cpp
> +        char* strEnd = s + strlen(s);
{}

2024-07-05 03:36 UTC, Brett-Constantinoff commented on engine/renderer/rhi/opengl/Opengl.cpp
> +        float desiredAspectRatio = 4.0f / 3.0f; // Max Schafer: "4:3 aspect ratio appears to look the best. Feel free to
{}

2024-07-05 03:36 UTC, Brett-Constantinoff commented on engine/renderer/rhi/opengl/Opengl.cpp
> +        float aspectRatio = static_cast<float>(width) / static_cast<float>(height);
{}

2024-07-05 03:37 UTC, Brett-Constantinoff commented on engine/renderer/rhi/opengl/Opengl.hpp
> +        uint32_t m_fbo                = 0;
{}

2024-07-05 03:37 UTC, Brett-Constantinoff commented on engine/renderer/rhi/opengl/Opengl.hpp
> +        uint32_t m_textureColorbuffer = 0;
{}

2024-07-05 03:37 UTC, Brett-Constantinoff commented on engine/renderer/rhi/opengl/Opengl.hpp
> +        uint32_t m_rbo                = 0;
{}

2024-07-05 03:37 UTC, Brett-Constantinoff commented on engine/renderer/utils/ImGuiSink.hpp
> +         spdlog::memory_buf_t formatted;
{}

2024-07-05 03:38 UTC, Brett-Constantinoff commented on engine/renderer/utils/ImGuiSink.hpp
> +   class ImGuiSink : public spdlog::sinks::base_sink<Mutex>
also i just noticed that this is in a utils folder, i think it would be better in a folder called sinks in core, that way all of our sinks are in the same location

2024-07-05 03:39 UTC, Brett-Constantinoff commented on engine/renderer/utils/ImGuiSink.hpp
> +   class ImGuiSink : public spdlog::sinks::base_sink<Mutex>
also should be a .inl file for the implementation since this is a template class

2024-07-05 03:39 UTC, Brett-Constantinoff commented on engine/renderer/utils/ImGuiSink.hpp
> +      std::vector<std::string> m_logMessages;
{}

2024-07-05 03:39 UTC, Brett-Constantinoff commented on engine/renderer/utils/ImGuiSink.hpp
> +      Mutex m_mutex;
{}

2024-07-05 03:39 UTC, Brett-Constantinoff commented on engine/renderer/utils/ImGuiSink.hpp
> +   using ImGuiSink_mt = ImGuiSink<std::mutex>;
GROSS, i think you can just use ImGuiSink<std::mutex> heres, its not much extra typing

2024-07-05 03:40 UTC, Brett-Constantinoff commented on engine/renderer/utils/ImGuiSink.hpp
> +      auto imguiSink = makeImguiSink();
{}

2024-07-05 03:40 UTC, Brett-Constantinoff commented on engine/renderer/utils/ImGuiSink.hpp
> +      auto logger = std::make_shared<spdlog::logger>("logger", imguiSink);
{}

2024-07-06 01:53 UTC, Brett-Constantinoff approved these changes
LGTM

2024-07-06 01:57 UTC, merged