Max/endless grid shader approach
Brett-Constantinoff/Quirk pull request #54
Opened 2024-07-13 02:06 UTC by maxsg5

2024-07-13 19:39 UTC, Brett-Constantinoff requested changes
left some comments

2024-07-13 19:39 UTC, Brett-Constantinoff commented on engine/renderer/rendering/MeshFactory.cpp
> +            mesh->vertices    = {{-1000.0f, 0.0f, -1000.0f},
why are these 1000?

2024-07-13 19:39 UTC, Brett-Constantinoff commented on engine/renderer/rendering/renderPasses/DefaultRenderPass.cpp
> +            glm::mat4 view =
id keep this as a constexpr, also direct list initialization

2024-07-13 19:39 UTC, Brett-Constantinoff commented on engine/renderer/rendering/renderPasses/DefaultRenderPass.cpp
> +            glEnable(GL_BLEND);
were these necessary in the end?

2024-07-13 19:39 UTC, Brett-Constantinoff commented on engine/resources/shaders/gridShaderProcedural.hlsl
> +out vec2 grid_position;
id keep all out variables prefaced with a 'o', also same naming as the rest of the repo, no snake case

2024-07-13 19:39 UTC, Brett-Constantinoff commented on engine/scene/Scene.cpp
> +                    if (name != "Grid")
doesnt look like the grid is being added to the vector of entities for the scene so is this check required?

2024-07-13 19:39 UTC, Brett-Constantinoff commented on engine/scene/Scene.hpp
> +        void                                                init(const std::shared_ptr<Scene> &self);
this seems weird, since scene isnt a static class, I would just do this in the constructor

2024-07-13 19:39 UTC, Brett-Constantinoff commented on engine/scene/Scene.hpp
> +        void                                                init(const std::shared_ptr<Scene> &self);
also, why dont you just create the grid in the scene manager?

2024-07-13 19:39 UTC, Brett-Constantinoff commented on engine/scene/EntityFactory.cpp
> +        // Set up MeshComponent
are these comments necessary?

2024-07-14 01:14 UTC, maxsg5 commented on engine/renderer/rendering/renderPasses/DefaultRenderPass.cpp
> +            glEnable(GL_BLEND);
Yes, the blending is necessary to render the grid. For example this is with it turned off:

 
![image](https://github.com/user-attachments/assets/1345137b-3324-4fa3-ad8c-1f3783c69ed9)

2024-07-14 01:31 UTC, maxsg5 commented on engine/scene/Scene.cpp
> +                    if (name != "Grid")
@Brett-Constantinoff Every single entity gets added to the vector of entities. It leverages the createEntity function which adds it to the vector.

2024-07-20 21:28 UTC, Brett-Constantinoff requested changes
Looks pretty good, left some comments

2024-07-20 21:28 UTC, Brett-Constantinoff commented on engine/display/DisplayWindow.cpp
> +        m_dimensions = glm::vec2(width, height);
why not just keep the width and height variables? Or if you realy want the vector, i would get rid of m_width and m_height

2024-07-20 21:28 UTC, Brett-Constantinoff commented on engine/display/DisplayWindow.cpp
> +        return static_cast<float>(m_near);
id keep these as doubles, you might lose some precision converting a double to float

2024-07-20 21:28 UTC, Brett-Constantinoff commented on engine/display/DisplayWindow.cpp
> +        return static_cast<float>(m_far);
Same thing as above

2024-07-20 21:28 UTC, Brett-Constantinoff commented on engine/display/DisplayWindow.hpp
> +        glm::vec2   m_dimensions{800.0f, 600.0f};
I would leave this as m_dimensions{}

2024-07-20 21:28 UTC, Brett-Constantinoff commented on engine/renderer/rendering/renderPasses/DefaultRenderPass.cpp
> +            glEnable(GL_BLEND);
since were not actually using blending for the grid (just discarding the pixel all together) i think this can be removed

2024-07-20 21:28 UTC, Brett-Constantinoff commented on engine/renderer/rendering/renderPasses/DefaultRenderPass.cpp
> +            glBlendFunc(GL_SRC_ALPHA, GL_ONE_MINUS_SRC_ALPHA);
same thing, this can probably be removed

2024-07-20 21:28 UTC, Brett-Constantinoff commented on engine/renderer/rendering/renderPasses/DefaultRenderPass.cpp
> +            glDisable(GL_BLEND);
remove

2024-07-20 21:28 UTC, Brett-Constantinoff commented on engine/renderer/rendering/renderPasses/DefaultRenderPass.cpp
> +            // gridMesh.isSubmitted = false;
remove

2024-07-20 21:28 UTC, Brett-Constantinoff commented on engine/renderer/utils/Utils.hpp
> +    inline const char *windowSizeUniformName{"uWindowSize"};
I dont think this or uCameraPosition is being used in the shaders, probably could be removed

2024-07-20 21:28 UTC, Brett-Constantinoff commented on engine/renderer/utils/Utils.hpp
> +    inline const char *modelUniformName{"uModel"};
this also isnt being used

2024-07-20 21:28 UTC, Brett-Constantinoff commented on engine/resources/shaders/gridShader.hlsl
> +vec3 UnprojectPoint(float x, float y, float z, mat4 view, mat4 projection) {
Keep style conventions in shaders, that means functions are pascalCase, brackets are on their own line etc. dont worry about direct list initialization, shaders dont support that

2024-07-20 21:28 UTC, Brett-Constantinoff commented on engine/scene/EntityFactory.cpp
> +        TransformComponent transformComponent{};
i dont think the grid would need a transform component, and i also dont think it would require the diffuse attribute for the material component

2024-07-20 21:28 UTC, Brett-Constantinoff commented on engine/scene/SceneManager.cpp
> +        m_grid = EntityFactory::createGridEntity(m_currentScene, "Grid", {0.64f, 0.64f, 0.64f, 1.0f},
I would prefer the grid be a part of the scene rather than the scene manager, you could instead have a method in the Scene class called addGrid that takes in a grid component (created elsewhere)

2024-07-20 21:28 UTC, Brett-Constantinoff commented on engine/scene/SceneManager.cpp
> +    std::shared_ptr<Entity> &
move to Scene

2024-07-20 21:28 UTC, Brett-Constantinoff commented on engine/scene/SceneManager.hpp
> +        [[nodiscard]] static std::shared_ptr<Entity>             &getGrid();
move to scene

2024-07-20 21:28 UTC, Brett-Constantinoff commented on engine/scene/components/MaterialComponent.hpp
> +        glm::mat4 model{};
remove

2024-07-20 21:28 UTC, Brett-Constantinoff commented on engine/renderer/rendering/renderPasses/DefaultRenderPass.cpp
> +            if (!gridMesh.isSubmitted)
can we move this to its own method in the render pass? that this method doesnt get too long

2024-07-21 03:01 UTC, maxsg5 commented on engine/scene/SceneManager.cpp
> +        m_grid = EntityFactory::createGridEntity(m_currentScene, "Grid", {0.64f, 0.64f, 0.64f, 1.0f},
I think that might be over-engineering it a bit, I can just add it like the rest of the entities in the default scene.

2024-07-21 18:10 UTC, Brett-Constantinoff requested changes
left 2 comments

2024-07-21 18:10 UTC, Brett-Constantinoff commented on engine/renderer/rendering/renderPasses/DefaultRenderPass.cpp
> +    void
like we talked about, i would leave the default implementation for now and we can create a new story for moving this to the scene

2024-07-21 18:10 UTC, Brett-Constantinoff commented on engine/resources/shaders/gridShader.hlsl
> +vec3 unprojectPoint(float x, float y, float z, mat4 view, mat4 projection) {
brackets on their own line

2024-07-26 21:46 UTC, Brett-Constantinoff approved these changes
lgtm

2024-07-26 21:47 UTC, merged